const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {createDurableJson}=require('../electron/durable-json.cjs');
const {createCollaborationStore}=require('../electron/collaboration-store.cjs');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wickrun-storage-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
test('corruption and access failures never yield empty storage',t=>{const root=fixture(t),file=path.join(root,'store.json');fs.writeFileSync(file,'{partial');const d=createDurableJson(file,{initial:()=>({})});assert.throws(()=>d.read(),/读取失败/);assert.throws(()=>d.write({}),/读取失败/);assert.equal(fs.readFileSync(file,'utf8'),'{partial');const denied=createDurableJson(file,{initial:()=>({}),io:{...fs,readFileSync(){throw Object.assign(Error('denied'),{code:'EACCES'});}}});assert.throws(()=>denied.read(),/denied/);});
test('failed fsync leaves disk and memory unchanged; restart retains custom data',t=>{const root=fixture(t),file=path.join(root,'store.json');let fail=false;const io={...fs,fsyncSync(fd){if(fail)throw Object.assign(Error('full'),{code:'ENOSPC'});fs.fsyncSync(fd);}};const d=createDurableJson(file,{initial:()=>({rows:[]}),io});d.write({rows:['custom']});fail=true;assert.throws(()=>d.write({rows:[]}),/full/);assert.deepEqual(d.read().rows,['custom']);assert.deepEqual(createDurableJson(file,{initial:()=>({})}).read().rows,['custom']);});
test('atomic replacement retains last backup; missing primary fails safely',t=>{const root=fixture(t),file=path.join(root,'store.json'),d=createDurableJson(file,{initial:()=>({})});d.write({v:1});d.write({v:2});assert.equal(JSON.parse(fs.readFileSync(file+'.prev','utf8')).v,1);fs.unlinkSync(file);assert.throws(()=>createDurableJson(file,{initial:()=>({})}).read(),/已有备份/);});
function project(){return {id:'p',members:[],workflows:[],tasks:[],runs:[],memories:[],schedules:[],files:[],preferences:{mode:'team'},settings:{maxConcurrent:1}};}
test('stale writers are rejected, no events lost and versions cannot mutate',t=>{const d=createCollaborationStore(fixture(t));const p=project();d.update(0,p);p.members.push({id:'m',name:'custom'});d.update(1,p);assert.throws(()=>d.update(1,project()),/已有更新/);assert.equal(d.read().projects.p.members[0].name,'custom');p.workflows.push({id:'f',versions:[{id:'v',graph:{x:4}}]});d.update(2,p);p.workflows[0].versions[0].graph.x=0;assert.throws(()=>d.update(3,p),/不可改写/);});
test('claim is unique and crash marks attempts uncertain without auto execution',t=>{const root=fixture(t),d=createCollaborationStore(root);require('./team-store-fixtures.cjs').install(d,root);d.claim('p','r');const data=d.read(),p=data.projects.p;p.runs[0].attempts.push({id:'a',nodeId:'node',status:'running'});d.update(data.revision,p);assert.throws(()=>d.claim('p','r'),/尚未就绪/);const next=createCollaborationStore(root).read().projects.p.runs[0];assert.equal(next.status,'uncertain');assert.equal(next.attempts[0].status,'uncertain');});
