'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createCollaborationStore}=require('../electron/collaboration-store.cjs');
const {install,prepareDelivery,approveDelivery}=require('./team-store-fixtures.cjs');
function fixture(t){const tmpRoot=fs.realpathSync.native(os.tmpdir()),root=fs.mkdtempSync(path.join(tmpRoot,'wickrun-team-ledger-test-'));t.after(()=>{assert.equal(path.dirname(root),tmpRoot);assert.ok(path.basename(root).startsWith('wickrun-team-ledger-test-'));fs.rmSync(root,{recursive:true,force:true});});const store=createCollaborationStore(root);install(store,root);return {root,store};}
function change(store,fn){const d=store.read(),p=d.projects.p;fn(p.runs[0],p);return store.update(d.revision,p);}
test('stored usage and execution counters cannot decrease or become invalid',t=>{const {store}=fixture(t);store.claim('p','r');change(store,r=>{r.tokens=20;r.visits.a=2;r.traversals.edge=3;});for(const fn of [r=>r.tokens=19,r=>r.tokens=NaN,r=>r.tokens=-1,r=>delete r.visits.a,r=>r.traversals.edge=0])assert.throws(()=>change(store,fn));assert.equal(store.read().projects.p.runs[0].tokens,20);});
test('events, discussion and completed attempt evidence remain append-only',t=>{const {store}=fixture(t);store.claim('p','r');change(store,(r,p)=>{r.events.push({id:'event',text:'real evidence'});r.attempts.push({id:'a',nodeId:'node',visit:1,startedAt:1,status:'completed',output:'real output',steps:[]});p.tasks[0].entries.push({id:'entry',text:'source'});});for(const fn of [r=>r.events=[],r=>r.events[0].text='rewritten',r=>r.attempts=[],r=>r.attempts[0].output='fake'])assert.throws(()=>change(store,fn),/不可/);assert.throws(()=>change(store,(_r,p)=>p.tasks[0].entries=[]),/不可/);});
test('snapshot and terminal state cannot be reset to evade prior outcomes',t=>{const {store}=fixture(t);assert.throws(()=>change(store,r=>r.projectSettings.roots=[]),/快照/);assert.throws(()=>change(store,r=>r.memorySnapshot.push({fake:true})),/快照/);store.claim('p','r');change(store,prepareDelivery);change(store,approveDelivery);assert.throws(()=>change(store,r=>r.status='ready'),/状态/);assert.throws(()=>store.claim('p','r'),/尚未就绪/);});
test('unknown run requires recorded verification before resuming',t=>{const {store}=fixture(t);store.claim('p','r');change(store,r=>r.status='uncertain');assert.throws(()=>change(store,r=>r.status='ready'),/状态/);assert.throws(()=>change(store,r=>r.status='paused'),/核实/);change(store,r=>{r.status='paused';r.events.push({id:'verified',kind:'verified',text:'checked external action state'});});assert.equal(store.claim('p','r').projects.p.runs[0].status,'running');});
test('restart conservatively charges outstanding reservations once without clearing known usage',t=>{const {store,root}=fixture(t);store.claim('p','r');change(store,r=>{r.tokens=10;r.reservations={'a:m':30};r.attempts.push({id:'a',status:'running'});});const recovered=createCollaborationStore(root).read().projects.p.runs[0];assert.equal(recovered.tokens,40);assert.deepEqual(recovered.reservations,{});assert.equal(recovered.status,'uncertain');assert.equal(recovered.attempts[0].status,'uncertain');assert.equal(recovered.events.some(e=>e.kind==='recovery_budget'),true);assert.equal(createCollaborationStore(root).read().projects.p.runs[0].tokens,40);});
test('waiting approval does not hide an interrupted parallel model branch',t=>{const {store,root}=fixture(t);store.claim('p','r');change(store,r=>{r.status='waiting_user';r.reservations={'branch:m':25};r.attempts.push({id:'branch',nodeId:'branch',status:'running'},{id:'approval',nodeId:'end',status:'waiting_user'});});const r=createCollaborationStore(root).read().projects.p.runs[0];assert.equal(r.status,'uncertain');assert.equal(r.attempts[0].status,'uncertain');assert.equal(r.tokens,25);});
test('completion rejects active branches but preserves historical failed retries',t=>{const {store}=fixture(t);store.claim('p','r');change(store,r=>{r.status='waiting_user';r.attempts.push({id:'a1',nodeId:'node',status:'failed',steps:[]},{id:'a2',nodeId:'node',status:'running',steps:[]});});assert.throws(()=>change(store,r=>r.status='completed'),/未核实/);change(store,r=>{r.attempts[1].status='completed';r.attempts[1].output='verified retry';prepareDelivery(r);});change(store,approveDelivery);assert.equal(store.read().projects.p.runs[0].attempts.filter(a=>a.nodeId==='node').length,2);});
